In [4]:
import pandas as pd 
import numpy as np 
import sqlalchemy
import os 
import sys
import datetime as dt
sys.path.insert(0, os.path.abspath(".."))

from Source.Database.db_con import get_engine

In [ ]:
# Connect to the Database
URL_SCM = "mysql+pymysql://root@localhost/scm"
URL_rainfall = "mysql+pymysql://root@localhost/rainfall"
# data = pd.read_sql("SELECT * FROM clean_data", engine)
rainfall_data = pd.read_sql("SELECT * FROM rainfall_raw", URL_rainfall)
SCM_data = pd.read_sql("SELECT * FROM clean_data", URL_SCM)

run run randa

CLeaning Rainfall Data

In [ ]:
rainfall_data.head() 
rainfall_dataa.columns()

,State,District,Date,Year,Month,Avg_rainfall,Agency_name,imported_at
0,Gujarat,Vadodara,2018-12-08,2018,12,0.000000,NRSC VIC MODEL,2026-01-20 16:33:32
1,Gujarat,Vadodara,2018-12-15,2018,12,0.000000,NRSC VIC MODEL,2026-01-20 16:33:32
2,Gujarat,Vadodara,2018-12-21,2018,12,0.000000,NRSC VIC MODEL,2026-01-20 16:33:32
3,Gujarat,Valsad,2018-07-27,2018,07,0.259955,NRSC VIC MODEL,2026-01-20 16:33:32
4,Gujarat,Valsad,2018-08-01,2018,08,0.016264,NRSC VIC MODEL,2026-01-20 16:33:32

In [ ]:
rainfall_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395486 entries, 0 to 395485
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   State         395486 non-null  object
 1   District      395486 non-null  object
 2   Date          395486 non-null  object
 3   Year          395486 non-null  object
 4   Month         395486 non-null  object
 5   Avg_rainfall  395486 non-null  float64
 6   Agency_name   395486 non-null  object
 7   imported_at   395486 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 24.1+ MB

In [ ]:
#Datetime
rainfall_data['Date'] = pd.to_datetime(rainfall_data['Date'], format = "%Y-%m-%d")
rainfall_data['Year'] = rainfall_data['Date'].dt.year
rainfall_data['Month'] = rainfall_data['Date'].dt.month

NameError: name 'pd' is not defined

In [40]:
rainfall_data.drop(columns=['imported_at', 'Agency_name', 'District'], inplace=True)

In [59]:
rainfall_GUJ = rainfall_data[rainfall_data['State'] == "Gujarat"]
groupby_GUJ = rainfall_GUJ.groupby(['Year', 'Month']).agg({'Avg_rainfall': 'mean', 'Date':'first'}, as_index=False)

In [60]:
groupby_GUJ.head()

            Avg_rainfall        Date
Year Month
2018 01         0.000000  2018-01-28
     02         0.000000  2018-02-01
     03         0.000000  2018-03-10
     04         0.000509  2018-04-02
     05         0.004596  2018-05-05

In [ ]:
start_date = '2020-04-01'
end_date = '2025-12-31',
rainfall_filtered = groupby_GUJ[(groupby_GUJ['Date'] >= start_date) & (groupby_GUJ['Date'] <= end_date)]

In [ ]:
SCM_data.head()

,Date,Product,QTY_MT,UOM,Season,State,FY,Month,Invoice_Value,Num_Month,Year
0,2020-04-01,Mahalaabh Gr.,2.000,MT,Kharif,Chhattisgarh,20-21,April,136500.00,4,2020
1,2020-04-01,Mahalaabh Gr.,11.525,MT,Kharif,Gujarat,20-21,April,777357.00,4,2020
2,2020-04-01,Mahalaabh Gr.,6.500,MT,Kharif,Karnataka,20-21,April,402906.00,4,2020
3,2020-04-01,Mahalaabh Gr.,8.125,MT,Kharif,Maharashtra,20-21,April,510019.12,4,2020
4,2020-04-01,Mahalaabh Gr.,1.525,MT,Kharif,Tamil Nadu,20-21,April,99277.50,4,2020

In [3]:
SCM_data_guj = SCM_data[SCM_data['State'] == 'Gujarat']

NameError: name 'SCM_data' is not defined